#!/usr/bin/env bash

# Create our vpc

VPC_ID=$(aws ec2 create-vpc --cidr-block "172.1.0.0/16" \
 --tag-specifications '{ "ResourceType": "vpc", "Tags": [ {"Key": "Name", "Value": "MyVPC"}, {"Key": "Environment", "Value": "Production"} ] }' \
 --region ap-south-1 \
 --query Vpc.VpcId \
 --output text)

 echo $VPC_ID

# create and IGW


# attach an IGW


# create a new subnet


# explicity attach subnet



# add a route for our RT to our IGW