#!/usr/bin/env bash
echo "== delete object"

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi
BUCKET_NAME=$1

# List objects in the bucket and create a JSON file for deletion
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query "Contents[].{Key: Key}" \
--output json | jq '{Objects: .}' > /tmp/delete_objects.json

# Delete the objects using the generated JSON file
aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json
