#!/usr/bin/env bash
echo "== list objects"

# check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi
BUCKET_NAME=$1

# No need to specify endpoint URL as ap-south-1 is compatible with most region endpoints
aws s3api list-objects-v2 --bucket $BUCKET_NAME 
