#!/usr/bin/env bash
echo "== put object"

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

# Check for filename 
if [ -z "$2" ]; then
    echo "There needs to be a file name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY
