#!/usr/bin/env bash
echo "==SYNC"

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "No filename prefix provided."
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# For storing the files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove the folder if it already exists
rm -rf $OUTPUT_DIR

# Create output folder
mkdir -p $OUTPUT_DIR

# Generate a random number to determine how many files to create
NUM_FILES=$(( RANDOM % 6 + 5 ))

for ((i=1; i<=$NUM_FILES; i++)); do
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    # Create a file with random content
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

# Display the created files
tree $OUTPUT_DIR

# Sync the output directory to the specified S3 bucket
aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
